snack_crud_project/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('snacks.urls'))
]

snacks/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomePageView , AboutPageView , SnacksListView , SnackDetailView , SnackCreateView , SnackUpdateView , SnackdeleteView


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about', AboutPageView.as_view(), name='about'),
    path('snacksList', SnacksListView.as_view(), name='snacksList'),
    path('<int:pk>/', SnackDetailView.as_view(), name='snack_details'),
    path('create/', SnackCreateView.as_view(), name="snack_create"),
    path('update/<int:pk>',SnackUpdateView.as_view(), name="snack_update"),
    path('delete/<int:pk>',SnackdeleteView.as_view(), name="snack_delete"),

]

snacks/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

# Create your models here.
class Snack(models.Model):
    name = models.CharField(max_length=255)
    description  = models.TextField(default='Snack description ')
    purchaser= models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
            return self.name
    
    def get_absolute_url(self):
        return reverse('snacksList')

snacks/views.py
from django.shortcuts import render
from django.views.generic import TemplateView , ListView , DetailView , CreateView , UpdateView , DeleteView
from .models import Snack
from django.urls import reverse_lazy

# Create your views here.
class HomePageView(TemplateView):
    template_name='home.html'

class AboutPageView(TemplateView):
    template_name='about.html'

class SnacksListView(ListView):
    template_name='snack_list.html'
    model = Snack

class SnackDetailView(DetailView):
    template_name='snack_detail.html'
    model=Snack

class SnackCreateView(CreateView):
     template_name='snack_creat.html'
     model=Snack
     fields= ['name', 'description', 'purchaser']

class SnackUpdateView(UpdateView):
    template_name='snack_update.html'
    model=Snack
    fields="__all__"
    success_url=reverse_lazy('snacksList')

class SnackdeleteView(DeleteView):
    template_name='snack_delete.html'
    model=Snack
    success_url=reverse_lazy('snacksList')

templates/about.html
{% extends 'sharing.html'%}

    {% block content %}

    <div class="text-center">
        <h1 class="text-4xl font-extrabold mb-4 text-gray-400 inline-block">About Page</h1>
        <p class="text-xl font-semibold  ml-2 fade-in ">Django test website</p>

    </div>

    
    {% endblock content %}

templates/home.html
{% extends 'sharing.html'%}

{% block content%}
<div class="text-center">
    <h1 class="text-4xl font-extrabold mb-4 text-gray-400 inline-block fade-in">Django</h1>
    <p class="text-xl font-semibold inline-block ml-2 inline-block fade-in ">makes it easier to build better Web apps more quickly and with less code.</p>
    <p class="text-gl font-semibold fade-in">The web framework for perfectionists with deadlines.</p>
</div>
{% endblock content%}

templates/sharing.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        html,
        body {
            height: 100%;
        }
        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 5;
            }
        }

        .fade-in {
            animation: fadeIn 5s ease-in-out;
        }
    </style>
</head>

<body class="flex flex-col justify-between min-h-screen bg-gray-900 text-white">
    <header class="bg-gray-800 shadow">
        <nav class="container mx-auto px-4 py-2">
            <div class="flex items-center justify-between">
                <a href="{% url 'home' %}" class="text-white font-semibold">Home</a>
                <a href="{% url 'about' %}" class="text-white font-semibold">About</a>
                <a href="{% url 'snacksList' %}" class="text-white font-semibold">snacks List</a>
            </div>
        </nav>
    </header>
    <main class="container mx-auto px-4 py-8">
        {% block content%}
        {% endblock content%}
    </main>
    <footer class="bg-gray-700 text-center py-4">
        <p class="text-gray-400">© 2023 Django Website. All rights reserved.</p>
    </footer>
</body>

</html>

templates/snack_creat.html
{% extends 'sharing.html' %}

{% block content %}
    <div class="container">
        <h1 class="text-4xl font-extrabold mb-4 text-gray-400 inline-block">Add new snack!</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="my-submit">Submit</button>
        </form>
    </div>
    <style>
        form input[type="text"],
        form textarea {
            color: rgb(255, 255, 255);
            background-color: #4d89cd96;
            border: none;
            border-radius: 4px;
            padding: 8px;
            margin-bottom: 8px;
        }


        textarea#id_description {
            width: 20%;
            height: 50px;
        }

      .my-submit {
        display: inline-block;
        padding: 8px 16px;
        background-color: #4d89cd96;
        color: #fff;
        text-decoration: none;
        border: none;
        border-radius: 4px;
        font-size: 14px;
        cursor: pointer;
        transition: background-color 0.3s ease;
      }
  
      .my-submit:hover {
        background-color: #347ad1;
      }
  
    </style>
{% endblock content %}

templates/snack_delete.html
{% extends 'sharing.html' %}

{% block content %}
    <h1>Delete a Snack!</h1>

    <form method="post">
        {% csrf_token %}

        <h3>Are you sure you want to delete {{ snack.name }}</h3>
        <button type="submit" class="my-submit">Delete</button>
        <button><a href="{% url 'snacksList' %}">Cancel</a></button>
    </form>

    <style>
        .my-submit {
            display: inline-block;
            padding: 8px 16px;
            background-color: #4d89cd96;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 4px;
            font-size: 14px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .my-submit:hover {
            background-color: #347ad1;
        }
    </style>
{% endblock %}

templates/snack_detail.html
{% extends 'sharing.html'%}

{% block content%}
<div class="text-center">
    <h1 class="text-4xl font-extrabold mb-4 text-gray-400 inline-block">Snacks Details</h1>
    <h2>{{snack.name}}</h2>
    <p>{{snack.description}}</p>
    <p>{{snack.purchaser}}</p>
{% endblock content%}

templates/snack_list.html
{% extends 'sharing.html' %}

{% block content %}
  <div class="text-center">
    <h1 class="text-4xl font-extrabold mb-4 text-gray-400 inline-block">Snacks list</h1>
    {% for snack in object_list %}
    <h3><a href="{% url 'snack_details' snack.pk%}">{{ snack.name }}</a></h3>
    <button class="Bupdate"><a href="{% url 'snack_update' snack.pk%}">Update</a></button>
    <button class="Bdelete"><a href="{% url 'snack_delete' snack.pk%}">Delete</a></button>
    {% endfor %}
  </div>
  
  <div class="text-center">
    <button class="my-button"><a href="{% url 'snack_create' %}">Add new one</a></button>
  </div>

  <style>
    .Bupdate,
    .Bdelete,
    .my-button {
      display: inline-block;
      padding: 8px 16px;
      background-color: #4d89cd96;
      color: #fff;
      text-decoration: none;
      border: none;
      border-radius: 4px;
      font-size: 14px;
      cursor: pointer;
      transition: background-color 0.3s ease;
      margin-top: 16px;
    }
    
    .Bupdate,
    .Bdelete,
    .my-button:hover {
      background-color: #347ad1;
    }
  </style>
{% endblock %}

templates/snack_update.html
{% extends 'sharing.html' %} 

{% block content %}
    <div class="container">
        <h1 class="text-4xl font-extrabold mb-4 text-gray-400 inline-block">Update the {{snack.name}}</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="my-submit">Submit</button>
        </form>
    </div>
    <style>
        form input[type="text"],
        form textarea {
            color: rgb(255, 255, 255);
            background-color: #4d89cd96;
            border: none;
            border-radius: 4px;
            padding: 8px;
            margin-bottom: 8px;
        }


        textarea#id_description {
            width: 20%;
            height: 50px;
        }

      .my-submit {
        display: inline-block;
        padding: 8px 16px;
        background-color: #4d89cd96;
        color: #fff;
        text-decoration: none;
        border: none;
        border-radius: 4px;
        font-size: 14px;
        cursor: pointer;
        transition: background-color 0.3s ease;
      }
  
      .my-submit:hover {
        background-color: #347ad1;
      }
  
    </style>
{% endblock content %}